name: cntdwn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  video_editor: ^3.0.0
  video_player: ^2.9.3
  image_picker: ^1.1.2
  path: ^1.9.1

  ffmpeg_kit_flutter:
    git:
      url: https://github.com/chebizarro/ffmpeg-kit.git
      ref: main
      path: flutter/flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
