name: vidrome
description: "All hail the new flesh."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  video_editor: ^3.0.0
  video_player: ^2.9.3
  image_picker: ^1.1.2
  path: ^1.9.1
  collection: ^1.19.1
  shared_preferences: ^2.5.2
  go_router: ^14.8.1
  logger: ^2.5.0
  dart_nostr: ^9.1.0
  crypto: ^3.0.6
  elliptic: ^0.3.11
  blurhash: ^1.2.0
  camera: ^0.11.1

  ffmpeg_kit_flutter:
    git:
      url: https://github.com/chebizarro/ffmpeg-kit.git
      ref: main
      path: flutter/flutter

  nip44:
    git:
      url: https://github.com/chebizarro/dart-nip44.git
      ref: master

  nip55:
    git:
      url: https://github.com/chebizarro/flutter-signer-plugin.git
      ref: v0.0.2
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
